import { useQuery } from '@apollo/client'
import { Button, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector, useDispatch } from 'react-redux'
import { increment, decrement, incrementByAmount } from '../features/counter/counterSlice'
import { greeting } from '../features/hellow/hellowSlice'
import { UserDocument } from '../generated'
import { RootState } from '../store/store'
import styles from '../styles/Home.module.css'
import { Input } from '@chakra-ui/react'
const Home: NextPage = () => {
  const { data, error, loading } = useQuery(UserDocument)

  const count = useSelector((state: RootState) => state.counter.value)

  const hellow = useSelector((state: RootState) => state.hellow.hellow)

  const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div>
          <div>
            <Button aria-label='Increment value' onClick={() => dispatch(increment())}>
              Increment
            </Button>
            <span>{count}</span>
            <Button aria-label='Decrement value' onClick={() => dispatch(decrement())}>
              Decrement
            </Button>
            <Button aria-label='Decrement value' onClick={() => dispatch(incrementByAmount(10))}>
              Increment 10
            </Button>
          </div>
          <div>
            <Input
              placeholder='Ingrese su nombre'
              onChange={(e) => dispatch(greeting(e.target.value))}
            />
            <Text>{hellow}</Text>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
